#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc query -M --names
bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d 0 1 2 3 4 5 6 7 8
#bspc monitor -g 1680x1050+0+0

bspc config border_width         0
bspc config window_gap          12
bspc config top_padding          30

bspc config normal_border_color \#024242
bspc config focused_border_color \#075454

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-center background.png
picom --conf ~/.config/picom/picom.conf &
pkill polybar
polybar -r lamiabarra &
